Melodic/Noetic support
ros-visualization/executive_smach_visualization pull request #42
Opened 2022-07-20 12:21 UTC by k-okada

rework of #39, as #39 mixes style change and noetic support, it also drop meldoic support.

2022-07-20 12:22 UTC, k-okada commented
@knorth55 can you check if  this works on your complex smach example? on both Meldoic / Noetic.

2022-07-20 13:07 UTC, knorth55 requested changes

2022-07-20 13:07 UTC, knorth55 commented on smach_viewer/scripts/smach_viewer.py
> +            local_data = pickle.loads(base64.b64decode(msg.local_data))
this chage causes error in `melodic`.
```
[ERROR] [1658322156.379389]: bad callback: <bound method SmachViewerFrame._status_msg_update of <__main__.SmachViewerFrame; proxy of <Swig Object of type 'wxFrame *' at 0x55a2221c2ce0> >>
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/knorth55/ros/melodic/src/ros-visualization/executive_smach_visualization/smach_viewer/scripts/smach_viewer.py", line 879, in _status_msg_update
    if container.update_status(msg):
  File "/home/knorth55/ros/melodic/src/ros-visualization/executive_smach_visualization/smach_viewer/scripts/smach_viewer.py", line 217, in update_status
    self._local_data._data = self._load_local_data(msg)
  File "/home/knorth55/ros/melodic/src/ros-visualization/executive_smach_visualization/smach_viewer/scripts/smach_viewer.py", line 191, in _load_local_data
    local_data = pickle.loads(base64.b64decode(msg.local_data))
  File "/usr/lib/python2.7/base64.py", line 78, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding
```

2022-07-20 13:17 UTC, knorth55 commented on smach_viewer/scripts/smach_viewer.py
> +            local_data = pickle.loads(base64.b64decode(msg.local_data))
I haven't checked yet, but this may be caused by multibyte language...

2022-07-20 13:24 UTC, knorth55 commented on smach_viewer/scripts/smach_viewer.py
> +            local_data = pickle.loads(base64.b64decode(msg.local_data))
Actually it is not related to multibyte language.
we have same error with `roseus_smach/sample/state-machine-ros-sample.l`

2022-07-20 13:39 UTC, k-okada commented on smach_viewer/scripts/smach_viewer.py
> +            local_data = pickle.loads(base64.b64decode(msg.local_data))
I think it is fixed now.

2022-07-20 13:53 UTC, knorth55 commented on smach_viewer/scripts/smach_viewer.py
> +            local_data = pickle.loads(base64.b64decode(msg.local_data))
Yes, thank you.

2022-07-20 13:56 UTC, knorth55 commented
Noetic is not yet tested, but I tested in Melodic.

I tried with english (singlebyte language) and it works in Melodic.
But I merged #40 to test with multibyte japanese but I got the following error.
I don't get this error in #40, so this is a bit weird...

```
[ERROR] [1658325349.225043]: label width 40 causes error
[ERROR] [1658325349.226524]: maybe multibyte word is in your label.
[ERROR] [1658325349.227478]: 'ascii' codec can't decode byte 0xe4 in position 2299: ordinal not in range(128)
[ERROR] [1658325349.228376]: changing width label width to 41
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/knorth55/ros/melodic/src/ros-visualization/executive_smach_visualization/smach_viewer/scripts/smach_viewer.py", line 1090, in _update_graph
    self.widget.subgraph_shapes,
AttributeError: 'WxDotWindow' object has no attribute 'subgraph_shapes'
```

2022-07-21 09:47 UTC, k-okada commented
@knorth55 If you revert, you can show  Japanese on melodic
```
-    parser = XDotParser(xdotcode)
+    parser = MyXDotParser(bytes(str(xdotcode).encode("utf-8")))
```

2022-07-21 14:01 UTC, knorth55 commented
@k-okada 
```
    parser = XDotParser(xdotcode)
```
works.

```
    parser = MyXDotParser(xdotcode)
```
does not works.

So, we should modify `MyXDotParser` to support multibyte language?

2022-07-22 09:32 UTC, knorth55 commented
@k-okada I make a PR for checking in melodic and noetic https://github.com/k-okada/executive_smach_visualization/pull/1

2022-07-23 07:56 UTC, merged